# Generated by Django 5.0 on 2023-12-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aircraft', '0002_aircraft_id_alter_aircraft_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
