# Generated by Django 5.0 on 2023-12-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aircraft', '0004_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
